from __future__ import annotations

import json
import os
import shutil
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
EXAMPLE_REPORT = ROOT / "examples" / "first-agent-report.md"
PUBLISH_EXAMPLE = ROOT / "scripts" / "publish-example.sh"
SERVER_TOKEN = "server-token-that-must-stay-private"
SESSION_SECRET = "session-secret-that-must-stay-private"
PASSWORD_HASH = "$argon2id$private-password-hash"
FAKE_CURL = r"""#!/usr/bin/env python3
import json
import os
import sys
from pathlib import Path

record = {
    "args": sys.argv[1:],
    "config": sys.stdin.read(),
    "server_token": os.environ.get("ARTIFACT_API_TOKEN"),
    "client_token": os.environ.get("ARTIFACT_RELAY_API_TOKEN"),
    "session_secret": os.environ.get("SESSION_SECRET_KEY"),
    "password_hash": os.environ.get("VIEW_PASSWORD_HASH"),
}
Path(os.environ["FAKE_CURL_LOG"]).write_text(json.dumps(record))
if os.environ.get("FAKE_CURL_FAIL"):
    print(os.environ.get("ARTIFACT_RELAY_API_TOKEN"), file=sys.stderr)
    print(os.environ.get("SESSION_SECRET_KEY"), file=sys.stderr)
    raise SystemExit(22)
print(json.dumps({"url": "https://public.example/a/first123"}))
"""


def test_first_agent_report_exercises_rich_markdown_safely() -> None:
    source = EXAMPLE_REPORT.read_text(encoding="utf-8")

    assert "| Status |" in source
    assert "- [x]" in source
    assert "```" in source
    assert "```mermaid" in source
    assert "ARTIFACT_API_TOKEN" not in source
    assert "SESSION_SECRET_KEY" not in source


def run_example(
    tmp_path: Path,
    args: list[str] | None = None,
    *,
    generated_env: bool = True,
    extra_env: dict[str, str] | None = None,
) -> tuple[subprocess.CompletedProcess[str], dict[str, object] | None]:
    checkout = tmp_path / "checkout"
    scripts = checkout / "scripts"
    examples = checkout / "examples"
    scripts.mkdir(parents=True)
    examples.mkdir()
    shutil.copy2(PUBLISH_EXAMPLE, scripts / "publish-example.sh")
    shutil.copy2(ROOT / "scripts" / "publish-file.sh", scripts / "publish-file.sh")
    shutil.copy2(EXAMPLE_REPORT, examples / "first-agent-report.md")

    marker = "# Generated by scripts/bootstrap.sh; keep this file private.\n"
    if not generated_env:
        marker = "# Manually created environment\n"
    (checkout / ".env").write_text(
        marker
        + f"ARTIFACT_API_TOKEN={SERVER_TOKEN}\n"
        + f"VIEW_PASSWORD_HASH='{PASSWORD_HASH}'\n"
        + f"SESSION_SECRET_KEY={SESSION_SECRET}\n"
        + "BASE_URL=http://localhost:8000\n"
        + "DATA_DIR=/data\n"
        + "COOKIE_SECURE=false\n"
        + "SHARE_LINKS_ENABLED=false\n",
        encoding="utf-8",
    )

    fake_bin = tmp_path / "bin"
    fake_bin.mkdir()
    curl = fake_bin / "curl"
    curl.write_text(FAKE_CURL, encoding="utf-8")
    curl.chmod(0o755)
    log = tmp_path / "curl.json"
    outside = tmp_path / "outside"
    outside.mkdir()
    (outside / ".env").write_text("ARTIFACT_API_TOKEN=wrong-cwd-token\n", encoding="utf-8")

    env = dict(os.environ)
    env.update(
        {
            "PATH": f"{fake_bin}{os.pathsep}{env['PATH']}",
            "FAKE_CURL_LOG": str(log),
            "ARTIFACT_RELAY_API_TOKEN": "wrong-ambient-client-token",
            "ARTIFACT_RELAY_BASE_URL": "https://wrong-ambient.example",
        }
    )
    if extra_env:
        env.update(extra_env)
    result = subprocess.run(  # noqa: S603
        [str(scripts / "publish-example.sh"), *(args or [])],
        cwd=outside,
        env=env,
        text=True,
        capture_output=True,
        check=False,
    )
    record = json.loads(log.read_text(encoding="utf-8")) if log.exists() else None
    return result, record


def test_publish_example_uses_checkout_env_and_delegates_fixed_report(tmp_path: Path) -> None:
    assert os.access(PUBLISH_EXAMPLE, os.X_OK)
    result, record = run_example(tmp_path)

    assert result.returncode == 0, result.stderr
    assert result.stdout == "https://public.example/a/first123\n"
    assert result.stderr == ""
    assert record is not None
    args = record["args"]
    assert isinstance(args, list)
    assert "http://localhost:8000/api/artifacts" in args
    assert any(
        str(argument).endswith("/examples/first-agent-report.md;type=text/markdown")
        for argument in args
    )
    assert record["config"] == f'header = "Authorization: Bearer {SERVER_TOKEN}"\n'


def test_publish_example_maps_token_and_scrubs_server_secrets(tmp_path: Path) -> None:
    result, record = run_example(tmp_path)

    assert result.returncode == 0, result.stderr
    assert record is not None
    assert record["client_token"] == SERVER_TOKEN
    assert record["server_token"] is None
    assert record["session_secret"] is None
    assert record["password_hash"] is None
    assert SERVER_TOKEN not in json.dumps(record["args"])
    assert SESSION_SECRET not in json.dumps(record["args"])
    assert PASSWORD_HASH not in json.dumps(record["args"])


def test_publish_example_accepts_one_valid_origin_override(tmp_path: Path) -> None:
    result, record = run_example(tmp_path, ["https://relay.example"])

    assert result.returncode == 0, result.stderr
    assert record is not None
    assert "https://relay.example/api/artifacts" in record["args"]


@pytest.mark.parametrize(
    "origin",
    ["http://relay.example", "https://user@relay.example", "https://relay.example/path"],
)
def test_publish_example_rejects_unsafe_origin_override(tmp_path: Path, origin: str) -> None:
    result, record = run_example(tmp_path, [origin])

    assert result.returncode != 0
    assert result.stdout == ""
    assert "ARTIFACT_RELAY_BASE_URL" in result.stderr
    assert record is None


def test_publish_example_rejects_non_bootstrap_env_before_sourcing(tmp_path: Path) -> None:
    result, record = run_example(tmp_path, generated_env=False)

    assert result.returncode != 0
    assert result.stdout == ""
    assert "bootstrap-generated .env" in result.stderr
    assert record is None


def test_publish_example_suppresses_secret_bearing_publish_failure(tmp_path: Path) -> None:
    result, _ = run_example(tmp_path, extra_env={"FAKE_CURL_FAIL": "1"})

    assert result.returncode != 0
    assert result.stdout == ""
    assert "Publish failed" in result.stderr
    for secret in (SERVER_TOKEN, SESSION_SECRET, PASSWORD_HASH):
        assert secret not in result.stdout
        assert secret not in result.stderr


def test_first_artifact_docs_share_one_safe_canonical_command() -> None:
    command = "./scripts/publish-example.sh"
    readme = (ROOT / "README.md").read_text(encoding="utf-8")
    self_host = (ROOT / "site" / "self-host" / "index.html").read_text(encoding="utf-8")

    assert readme.count(command) == 1
    assert self_host.count(command) == 1
    assert "Authorization: Bearer" not in readme
    assert "Authorization: Bearer" not in self_host
    assert "SAMPLE_FILE" not in self_host
    assert "ARTIFACT_URL" not in self_host


def test_generic_agent_guide_links_to_executable_first_example() -> None:
    guide = (ROOT / "docs" / "GENERIC_AGENT_PUBLISHING.md").read_text(encoding="utf-8")

    assert "[bounded first-artifact example](../scripts/publish-example.sh)" in guide
