#!/usr/bin/env bash
set -euo pipefail

ENV_FILE="${ENV_FILE:-.env}"
IMAGE="${ARTIFACT_RELAY_IMAGE:-artifact-relay:1.0.0}"

if [[ -e "$ENV_FILE" ]]; then
  printf 'Refusing to overwrite existing %s\n' "$ENV_FILE" >&2
  exit 1
fi

for command in docker openssl; do
  command -v "$command" >/dev/null 2>&1 || {
    printf 'Required command not found: %s\n' "$command" >&2
    exit 1
  }
done

printf 'Viewer password (at least 12 characters): ' >&2
IFS= read -r -s PASSWORD
printf '\nRepeat viewer password: ' >&2
IFS= read -r -s PASSWORD_CONFIRM
printf '\n' >&2

if [[ "$PASSWORD" != "$PASSWORD_CONFIRM" ]]; then
  printf 'Passwords do not match.\n' >&2
  exit 1
fi
if (( ${#PASSWORD} < 12 )); then
  printf 'Password must be at least 12 characters.\n' >&2
  exit 1
fi

# Feed the password over stdin: it never appears in process arguments, shell history, or .env.
# The outer script already collected and confirmed it without echo, so the container only hashes.
VIEW_PASSWORD_HASH="$(printf '%s' "$PASSWORD" |
  docker run --rm -i --entrypoint python "$IMAGE" -c \
    'import sys; from artifact_relay.hashing import hash_password; print(hash_password(sys.stdin.read()))')"
unset PASSWORD PASSWORD_CONFIRM
[[ "$VIEW_PASSWORD_HASH" == \$argon2id\$* ]] || {
  printf 'The image did not return an Argon2id hash.\n' >&2
  exit 1
}

ARTIFACT_API_TOKEN="$(openssl rand -base64 36 | tr -d '\n')"
SESSION_SECRET_KEY="$(openssl rand -base64 48 | tr -d '\n')"

env_dir="$(dirname "$ENV_FILE")"
mkdir -p "$env_dir"
tmp="$(mktemp "$env_dir/.artifact-relay-env.XXXXXX")"
trap 'rm -f "$tmp"' EXIT
chmod 0600 "$tmp"
{
  printf '# Generated by scripts/bootstrap.sh; keep this file private.\n'
  printf 'ARTIFACT_API_TOKEN=%s\n' "$ARTIFACT_API_TOKEN"
  printf "VIEW_PASSWORD_HASH='%s'\\n" "$VIEW_PASSWORD_HASH"
  printf 'SESSION_SECRET_KEY=%s\n' "$SESSION_SECRET_KEY"
  printf 'BASE_URL=http://localhost:8000\n'
  printf 'DATA_DIR=/data\n'
  printf 'COOKIE_SECURE=false\n'
  printf 'SHARE_LINKS_ENABLED=false\n'
  printf 'FORWARDED_ALLOW_IPS=127.0.0.1\n'
} > "$tmp"

# A same-filesystem hard link is an atomic no-clobber install.
if ! ln "$tmp" "$ENV_FILE" 2>/dev/null; then
  printf 'Refusing to overwrite existing %s\n' "$ENV_FILE" >&2
  exit 1
fi
rm -f "$tmp"
trap - EXIT
printf 'Created %s with mode 0600. Start with: docker compose up -d\n' "$ENV_FILE"
