#!/bin/sh
set -eu

fail() {
    printf '%s\n' "$1" >&2
    exit 2
}

[ "$#" -le 1 ] || fail "Usage: scripts/publish-example.sh [BASE_URL]"

script_dir=$(CDPATH= cd "$(dirname "$0")" && pwd)
repository_dir=$(dirname "$script_dir")
base_url_override=${1:-}

(
    env_file=$repository_dir/.env
    [ -f "$env_file" ] && [ -r "$env_file" ] ||
        fail "Run scripts/bootstrap.sh first to create the bootstrap-generated .env."

    marker=
    IFS= read -r marker <"$env_file" || :
    [ "$marker" = "# Generated by scripts/bootstrap.sh; keep this file private." ] ||
        fail "Refusing to source an environment that is not the bootstrap-generated .env."

    set -a
    # bootstrap.sh writes shell-safe assignments and the marker above identifies that format.
    . "$env_file"
    set +a

    : "${ARTIFACT_API_TOKEN:?Bootstrap-generated .env is missing ARTIFACT_API_TOKEN.}"
    : "${BASE_URL:?Bootstrap-generated .env is missing BASE_URL.}"
    ARTIFACT_RELAY_API_TOKEN=$ARTIFACT_API_TOKEN
    ARTIFACT_RELAY_BASE_URL=${base_url_override:-$BASE_URL}
    export ARTIFACT_RELAY_API_TOKEN ARTIFACT_RELAY_BASE_URL

    unset ARTIFACT_API_TOKEN VIEW_PASSWORD_HASH SESSION_SECRET_KEY

    exec "$script_dir/publish-file.sh" "$repository_dir/examples/first-agent-report.md"
)
